version: '3.7'
services:
  app: &app
    build: .
    volumes:
      - bundle_cache:/bundle
      - .:/app
      - node_modules_cache:/app/node_modules
    network_mode: "host"

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    <<: *app
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: "ifd_web"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker
      - delayed_job

  webpacker:
    <<: *app
    command: ./bin/webpack-dev-server
    container_name: "webpacker"
    ports:
      - '3035:3035'

  delayed_job:
    <<: *app
    tty: true
    stdin_open: true
    command: bundle exec rails jobs:work
    container_name: "ifd_job"
    depends_on:
      - db
      - webpacker

volumes:
  bundle_cache:
  node_modules_cache:
