name: CI
on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.6

      - name: Ruby gem cache dependencies
        uses: actions/cache@preview
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Install pg gem dependency
        env:
          RAILS_ENV: test
        run: sudo apt-get -yqq install libpq-dev

      - name: bundle install
        env:
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Setup Database
        run: |
          cp config/database.yml.github-actions config/database.yml
          bin/rails db:prepare --trace
        env:
          RAILS_ENV: test

      - name: Run RSpec
        run: bundle exec rspec
        env:
          RAILS_ENV: test
